from .core import (ENDFLAG,
                   STARTFLAG,
                   DATATYPES,
                   INFtoVARS,
                   SIGPROCKEYS,
                   FORMATCHARS,
                   MACHINEtoID,
                   IDtoMACHINE,
                   TELESCOPEtoID,
                   IDtoTELESCOPE,
                   BESTPROFtoVARS,
                   TELESCOPEtoMAXHA)
