FORMATCHARS = {
    'pad': ('x', None),
    'bool': ('?', 1),
    'char': ('c', 1),
    'signed_char': ('b', 1),
    'unsigned_char': ('B', 1),
    'short': ('h', 2),
    'unsigned_short': ('H', 2),
    'int': ('i', 4),
    'unsigned_int': ('I', 4),
    'long': ('l', 4),
    'unsigned long': ('L', 4),
    'long_long': ('q', 8),
    'unsigned_long_long': ('Q', 8),
    'float': ('f', 4),
    'double': ('d', 8),
}

INFtoVARS = {
    'Data file name without suffix': ['basename', str],
    'Telescope used': ['telescopeID', str],
    'Instrument used': ['machineID', str],
    'Object being observed': ['srcname', str],
    'J2000 Right Ascension (hh:mm:ss.ssss)': ['srcRA', str],
    'J2000 Declination     (dd:mm:ss.ssss)': ['srcDEC', str],
    'Epoch of observation (MJD)': ['mjd', float],
    'Barycentered?           (1 yes, 0 no)': ['barycentric', int],
    'Number of bins in the time series': ['nbins', int],
    'Width of each time series bin (sec)': ['tsamp', float],
    'Any breaks in the data? (1 yes, 0 no)': ['break', int],
    'Type of observation (EM band)': ['obstype', str],
    'Beam diameter (arcsec)': ['beamdiam', float],
    'Dispersion measure (cm-3 pc)': ['dm', float],
    'Central freq of low channel (MHz)': ['cfreq', float],
    'Total bandwidth (MHz)': ['bw', float],
    'Number of channels': ['nchan', int],
    'Channel bandwidth (MHz)': ['chanbw', float],
}
