PSRFITSKEYS = {
    "PRIMARY": [
        "FITSTYPE",
        "TELESCOP",
        "OBSERVER",
        "SRC_NAME",
        "FRONTEND",
        "BACKEND",
        "PROJID",
        "DATE-OBS",
        "FD_POLN",
        "RA",
        "DEC",
        "OBSFREQ",
        "OBSNCHAN",
        "OBSBW",
        "BMIN",
        "CHAN_DM",
        "STT_IMJD",
        "STT_SMJD",
        "STT_OFFS",
        "STT_LST",
        "TRK_MODE",
    ],
    "SUBINT": [
        "TBIN",
        "NCHAN",
        "NPOL",
        "POL_TYPE",
        "NCHNOFFS",
        "NSBLK",
        "NBITS",
        "NAXIS2",
        "NSUBOFFS",
        "ZERO_OFF",
    ],
    "SUBINT-HDU": [
        "OFFS_SUB",
        "DATA",
        "TEL_AZ",
        "TEL_ZEN",
        "DAT_FREQ",
        "DAT_WTS",
        "DAT_OFFS",
        "DAT_SCL",
    ],
}

PSRFITSTEMP = [
    "From the PSRFITS file {:s}:",
    "                       HDUs = {:s}",
    "                  Telescope = {:s}",
    "                   Observer = {:s}",
    "                Source Name = {:s}",
    "                   Frontend = {:s}",
    "                    Backend = {:s}",
    "                 Project ID = {:s}",
    "            Obs Date String = {:s}",
    "  MJD start time (DATE-OBS) = {:5d.14s}",
    "     MJD start time (STT_*) = {:19.14",
    "                   RA J2000 = {:s}",
    "             RA J2000 (deg) = {:-17.15g",
    "                  Dec J2000 = {:s}",
    "            Dec J2000 (deg) = {:-17.15g}",
    "                  Tracking? = {:s}",
    "              Azimuth (deg) = {:-.7g}",
    "           Zenith Ang (deg) = {:-.7g}",
    "          Polarisation type = {:s}",
    "            Number of polns = {:s}",
    "         Polarisation order = {:s}",
    "           Sample time (us) = {:-17.15g}",
    "         Central freq (MHz) = {:-17.15g}",
    "          Low channel (MHz) = {:-17.15g}",
    "   Orig Channel width (MHz) = {:-17.15g}",
    "    Orig Number of channels = {:d}",
    "    DM used for chan dedisp = {:-17.15g}",
    "      Total Bandwidth (MHz) = {:-17.15g}",
    "         Spectra per subint = {:d}",
    "            Starting subint = {:d}",
    "           Subints per file = {:d}",
    "           Spectra per file = {:d}",
    "        Time per file (sec) = {:-.12g}",
    "              FITS typecode = {:s}",
    "                DATA column = {:d}",
    "            Bits per sample = {:d}",
    "          Bytes per spectra = {:d}",
    "        Samples per spectra = {:d}",
    "           Bytes per subint = {:d}",
    "         Samples per subint = {:d}",
    "              Need scaling? = {:s}",
    "              Need offsets? = {:s}",
    "              Need weights? = {:s}",
    "        Need band inverted? = {:s}",
]
